share_with_me/drive/urls.py
from django.urls import path, include

from drive.views import index, images

app_name = 'drive'

images_patterns = [
    path('courses/', images.courses, name='courses'),
    path('courses/<int:course>/', images.specialty, name='specialty'),
    path('courses/<int:course>/<str:specialty>/', images.subject, name='subject'),
    path('courses/<int:course>/<str:specialty>/<str:subject>/',
         images.detail_subject, name='detail_subject'),
    path('courses/<path:path>/upload', images.upload_file, name='upload_file'),
    path('courses/<path:path>/list/', images.list, name='list'),
    path('courses/<path:path>/<int:image_id>/', images.detail, name='detail'),
    path('courses/<path:path>/<int:image_id>/add-comment', images.add_comment, name='add_comment'),
    path('search/', images.search, name='search'),
]

home_patterns = [
    path('', images.base, name='base'),
]

about_patterns = [
    path('', images.about, name='about')
]

request_patterns = [
    path('', images.request_folder, name='request_folder')
]

urlpatterns = [
    path('', index, name='index'),
    path('', include((images_patterns, 'images'))),
    path('home/', include((home_patterns, 'home'))),
    path('about-us/', include((about_patterns, 'info'))),
    path('request/', include((request_patterns, 'request'))),
]

share_with_me/share_with_me/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# MEDIA_ROOT = "media"
# MEDIA_URL = '/'

urlpatterns = [
    path('', include('drive.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# ] + static(MEDIA_URL, document_root=MEDIA_ROOT)

share_with_me/drive/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError


class Courses(models.Model):
    course = models.IntegerField(validators=[MaxValueValidator(4), MinValueValidator(1)])
    specialty = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)
    path = models.TextField(primary_key=True, blank=True)

    def save(self, *args, **kwargs):
        self.path = f'{self.course}/{self.specialty}/{self.subject}'
        super().save(*args, **kwargs)


def content_file_name(instance, filename):
    return '{0}/{1}/{2}/{3}'.format(instance.course_path.course,
                                    instance.course_path.specialty,
                                    instance.course_path.subject,
                                    filename)


class Image(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)
    course_path = models.ForeignKey(Courses, to_field='path', on_delete=models.CASCADE)
    image = models.ImageField(default='static/default_img.png', upload_to=content_file_name)
    file = models.FileField(upload_to=content_file_name, blank=True, null=True)

    def clean(self):
        super().clean()
        if not self.file and self.image == 'static/default_img.png':
            raise ValidationError('You should upload a file.')

    def image_tag(self):
        if self.file:
            return mark_safe(f'<img src="{self.image.url}" title="{self.file.url}" width="250" height="150" />')
        else:
            return mark_safe(f'<img src="{self.image.url}" title="{self.image.url}" width="250" height="150" />')

    def path_to_file(self):
        return str(self.course_path)

    image_tag.short_description = 'ImageTag'
    image_tag.allow_tags = True

    def __str__(self):
        return str(self.image)


class Comments(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    username = models.CharField(max_length=50)
    comment = models.TextField()
    rating = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    file = models.ForeignKey(Image, on_delete=models.CASCADE)


class Requests(models.Model):
    username = models.CharField(max_length=50)
    course = models.IntegerField(validators=[MaxValueValidator(4), MinValueValidator(1)])
    specialty = models.CharField(max_length=30)
    subject = models.CharField(max_length=30, blank=True, null=True)

share_with_me/drive/views.py
from django.shortcuts import render

# Create your views here.

share_with_me/drive/views/images.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from drive.models import Image, Courses, Comments, Requests

from django import forms
from django.db.models import Q
from django.db.models import Sum


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('description', 'file',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('username', 'comment', 'rating')


class RequestForm(forms.ModelForm):
    class Meta:
        model = Requests
        fields = ('username', 'course', 'specialty', 'subject')


def base(request):
    return render(
        request,
        'images/base.html',
    )


def courses(request):
    return render(
        request,
        'images/courses.html',
        {
            'courses': Courses.objects.values_list('course', flat=True).distinct().order_by('course')
        }
    )


def specialty(request, course):
    return render(
        request,
        'images/specialty.html',
        {
            'course': course,
            'specialties': Courses.objects.values_list('specialty', flat=True).filter(course=course).distinct()
        }
    )


def subject(request, course, specialty):
    return render(
        request,
        'images/subject.html',
        {
            'course': course,
            'specialty': specialty,
            'subjects': Courses.objects.values_list('subject', flat=True).filter(course=course, specialty=specialty)
        }
    )


def detail_subject(request, course, specialty, subject):
    return render(
        request,
        'images/detail_subject.html',
        {
            'course': Courses.objects.filter(course=course, specialty=specialty, subject=subject).first(),
        }
    )


def upload_file(request, path):
    if request.method == "POST":
        flag = False
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            if 'image/' in str(request.FILES):
                instance.image = instance.file
                flag = True
            course = Courses.objects.filter(path=path).first()
            instance.course_path = course
            instance.save()
            if flag is True:
                instance.file = None
                instance.save(update_fields=['file'])
            return redirect(reverse('drive:images:list',
                                    args=[path, ]))
        else:
            return render(
                request,
                'images/upload_file.html',
                {
                    'form': form,
                    'path': path,
                }
            )
    else:
        form = ImageForm()
        return render(
            request,
            'images/upload_file.html',
            {
                'form': form,
                'path': path,
            }
        )


def list(request, path):
    course = Courses.objects.filter(path=path).first()
    return render(
        request,
        'images/list.html',
        {
            'course': course,
            'path': path,
            'images': Image.objects.filter(course_path=path)
        }
    )


def detail(request, path, image_id):
    image = get_object_or_404(Image, id=image_id)
    comments = Comments.objects.filter(file=image)
    rating = 0
    avg_rating = 0
    if comments:
        rating = comments.aggregate(Sum('rating'))['rating__sum']
        if rating % len(comments) != 0:
            avg_rating = round(rating / len(comments), 1)
        else:
            avg_rating = rating // len(comments)
    return render(
        request,
        'images/detail.html',
        {
            'path': path,
            'image': image,
            'comments': comments,
            'avg_rating': avg_rating,
        }
    )


def search(request):
    something_found = False
    if request.GET.get('q'):
        message = request.GET['q']
        found_subjects = Courses.objects.filter(subject__contains=message)
        found_specialties = Courses.objects.values_list('course', 'specialty')\
                                           .filter(specialty__contains=message)\
                                           .distinct().order_by('course')
        found_files = Image.objects.filter(Q(image__contains=message) | Q(file__contains=message))
        if found_subjects or found_specialties or found_files:
            something_found = True

        return render(
            request,
            'images/search.html',
            {
                'something_found': something_found,
                'found_subjects': found_subjects,
                'found_specialties': found_specialties,
                'found_files': found_files,
                'error': 'No mathes found.',
            }
        )
    else:
        return render(
            request,
            'images/search.html',
            {
                'something_found': something_found,
                'error': 'You submitted an empty search',
            }
        )


def add_comment(request, path, image_id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        file = Image.objects.filter(id=image_id).first()

        if form.is_valid() and file:
            instance = form.save(commit=False)
            instance.file = file
            instance.save()
            return redirect(reverse('drive:images:detail',
                                    args=[path, image_id]))
        else:
            return render(
                request,
                'images/add_comment.html',
                {
                    'form': form,
                    'path': path,
                    'image_id': image_id,
                }
            )
    else:
        form = CommentForm()
        return render(
            request,
            'images/add_comment.html',
            {
                'form': form,
                'path': path,
                'image_id': image_id,
            }
        )


def about(request):
    return render(
        request,
        'images/about.html',
    )


def request_folder(request):
    if request.method == "POST":
        form = RequestForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            if instance.subject:
                course = Courses.objects.filter(course=instance.course,
                                                specialty=instance.specialty,
                                                subject=instance.subject).first()
            else:
                course = Courses.objects.filter(course=instance.course,
                                                specialty=instance.specialty).first()
            if not course:
                instance.save()
                return redirect(reverse('drive:home:base'))
            else:
                return render(
                    request,
                    'images/request_folder.html',
                    {
                        'form': form,
                        'error': 'It already exists. Try the search bar!'
                    }
                )
        else:
            return render(
                request,
                'images/request_folder.html',
                {
                    'form': form,
                }
            )
    else:
        form = RequestForm()
        return render(
            request,
            'images/request_folder.html',
            {
                'form': form,
            }
        )

share_with_me/drive/templates/images/about.html
{% extends "images/base.html" %} {% block content %}
<div class="courses">
    <h1>About Us</h1>
    <div style="text-align: center;">
        <p style="font-size: 20px">We are</p>
        <div class="zoom" style="display:inline-block;">
            <a style ="font-size:20px;" href="https://github.com/hpmalinova">Hrisi</a>
            <p style="display:inline-block;">&</p>
            <a style ="font-size:20px;" href="https://github.com/TsvetomirTsvetkov">Tseko</a>
        </div>

        <p>(Team Crocodile)<br><br>and this is our final project for HackBulgaria's<br>"Programming 101 with Python"<br>course.</p>
        <div class="zoom">
            <h1 style="font-size:20px;"><a href="https://github.com/hpmalinova/Share-with-me">Project Repository</a></h1>
        </div>
    </div>
</div>
{% endblock %}

share_with_me/drive/templates/images/add_comment.html
{% extends "images/base.html" %} {% block content %}
<div class="courses">
    <h1>Add comment:</h1>
    <form method="POST" enctype="multipart/form-data">
        <div class="center">
            <p><label style="text-align:center;" for="id_username">Username:</label></p>
            <input type="text" name="username" maxlength="50" required="" id="id_username">
            <p><label for="id_comment">Comment:</label></p>
            <textarea name="comment" cols="40" rows="4" required="" id="id_comment"></textarea>
            <p><label for="id_rating">Rating:</label></p>
            <!-- <input type="number" name="rating" value="1" required="" id="id_rating" min="1" max="5"> -->
          {% csrf_token %}
          <!-- {{ form.as_p }} -->
          <div class="radioGroupBelow">
            <span class="star-rating">
            <label>1
              <input type="radio" name="rating" value="1" id="id_rating" required=""><i></i>
            </label>
            <label>2
              <input type="radio" name="rating" value="2" id="id_rating" required=""><i></i>
            </label>
            <label>3
              <input type="radio" name="rating" value="3" id="id_rating" required=""><i></i>
            </label>
            <label>4
              <input type="radio" name="rating" value="4" id="id_rating" required=""><i></i>
            </label>
            <label>5
              <input type="radio" name="rating" value="5" id="id_rating" required=""><i></i>
            </label>
            </span>
            <br>
          </div>
          <button type="submit">Add Comment</button>
      </div>
    </form>
    <h3 style="text-align:center;"><a href="{% url 'drive:images:detail' path image_id %}">Go to file view</a></h3>
</div>
{% endblock %}

share_with_me/drive/templates/images/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'drive/style.css' %}">
<style>
    body {
        background-color: #eaeaea;
        margin:0;
    }
</style>

<div class="menu">
        
        <!-- <span style="z-index: -50;" class="dot2"></span> -->
        
        <ul>
            <li style="float: left; "><a href="javascript:history.back()">Back</a></li>
            <li style="float:left; padding-left: 150px; font-weight: bold;"><a href="{% url 'drive:home:base' %}">ShareWithMe</a></li>
            <li><a href="{% url 'drive:info:about' %}">About Us</a></li>
            <li><a href="{% url 'drive:request:request_folder' %}">Request</a></li>
            <li><a href="{% url 'drive:images:courses' %}">Courses</a></li>
            <li><a href="{% url 'drive:home:base' %}">Home</a></li>
            <li><a href="{% url 'drive:home:base' %}"><img src="/static/mg.png" alt="Search" width="22.5" height="22.5"></a></li>
        </ul>
        {% if request.path == "/home/" %}
        
        <span class="dot"></span>
        <div class="center findforme">
            <h1 style="color: #949494;">Find For Me</h1>
        </div>
        <div class="center sharewithme">
            <form method="GET" action="{% url 'drive:images:search'%}" id="searchform">
                <input style="color: #949494; font-weight: bold; font-size: 25px; background-color: #FFFFFF; border-radius: 0.3em;" size="16" class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search..."/>
                <button style="border: none; height:32; background-color: #ff0040;" type="submit"><img src="/static/mg.png" alt="Search" width="22.5" height="22.5"></button>
            </form>
            <p>You can use the search engine<br>or just navigate the site<br>through the menu<br>on top</p>
        </div>
        {% endif %}
</div>
{% block content %} {% endblock %}

share_with_me/drive/templates/images/courses.html
{% extends "images/base.html" %} {% block content %}

<div class="courses">
    <h1>Choose Course</h1>
    <div style="position: absolute; top:39.5%; right:80%;" class="circle"></div>
    <div style="position: absolute; top:39.5%; right:15%;" class="circle"></div>
    {% if courses %}
        <ul>
          {% for course in courses %}
          <li><a href="{% url 'drive:images:specialty' course %}">Year: {{ course }}</a></li>
          {% endfor %}
        </ul>
        <div class="center_text">
            <p>Choose the year for which<br>you want to<br>lookup / upload</p>
        </div>
    {% else %}
        <div class="center sharewithme">
            <p style="font-size: 30px;"><strong>No courses yet.</strong></p>
        </div>
    {% endif %} 
</div>
{% endblock %}

share_with_me/drive/templates/images/detail.html
{% extends "images/base.html" %} {% block content %}
<div class="courses">
    <div class="center">
        <p style="display:inline; text-align: left;"> Uploaded: {{image.created_at}} </p>
        {% if avg_rating %}
            <p style="font-size:25px;"><strong>* Rating: {{avg_rating}}/5 *</strong></p>
        {% endif %}

    </div>
    {% if image.description %}
        <div class="center">
            <p style="text-align:center; display:inline; top:50%"> Description: {{image.description}} </p>
        </div>
    {% endif %}

    {% if image.file %}
        <div class="center">
            <button style=><a href="{{image.file.url}}">Download File</a></button>
        </div>
    {% else %}
        <div class="center">
        <img style="max-height: 50%; max-width: 50%;" src="{{image.image.url}}" />
        </div>
    {% endif %}


    <hr>
    <div class="center">
        <h1 style="font-size:25px;"><a href="{% url 'drive:images:add_comment' path image.id%}">Add comment</a></h1>
    </div>
    <h1 style="font-size:25px;"> Comments: </h1>
    
    {% if comments %}
    <div class="center">
        <ul>
          {% for comment in comments %}
            <div style="width:500px; margin:0 auto; display:block;word-wrap: break-word;">
                
                <div style="background-color: #ff0040;">
                    <p style="color:#ffffff;background-color: #ff0040;text-align: left; padding-left:5px;"><strong>{{comment.username}} said:</strong></p>
                </div>
                <div style="border:3px solid #ff0040; background-color: #ffffff;">
                    <p style="color:#737373; text-align: left; padding-left:5px;">Rated: {{comment.rating}}/5</p>
                    <p style="color:#737373; text-align: left; padding-left:5px;">{{comment.comment}}</p>
                    <p style="color:#737373;text-align: right;">{{comment.created_at}}</p>
                </div>
            </div>
          {% endfor %}
        </ul>
        {% else %}
        <p style="text-align:center;"><strong>No comments yet.</strong></p>
        {% endif %}
    </div>
</div>
{% endblock %}

share_with_me/drive/templates/images/detail_subject.html
{% extends "images/base.html" %} {% block content %}

<div class="courses">
    <h1><strong>{{ course.subject }} </strong></h1>
    <ul style="text-align: center;">
        <li style="display: inline; padding-right: 100px;"><a href="{% url 'drive:images:upload_file' course.path %}">Upload file</a></li>
        <li style="display: inline; padding-left: 100px;"><a href="{% url 'drive:images:list' course.path %}">Show files</a></li>
    </ul>
    <div style="position: absolute; top:33%; right:50%;" class="rectangle"></div>
    <div style="position: absolute; top:39.5%; right:80%;" class="circle"></div>
    <div style="position: absolute; top:39.5%; right:15%;" class="circle"></div>
    <div class="center_text">
        <p style="margin-top: 10em;">You can either look through the files<br>or upload one yourself</p>
    </div>
</div>
{% endblock %}

share_with_me/drive/templates/images/list.html
{% extends "images/base.html" %} {% block content %}

<div class="courses">
    <ul class="center sharewithme">
        <h1>{{course.subject}} files</h1>
        <h2 style="font-size:25px;"><a href="{% url 'drive:images:upload_file' path %}">Upload file</a></h2>
        {% if images %}
            {% for image in images %}
                <li style="position:static;display:inline-table;"><a href="{% url 'drive:images:detail' path image.id %}">{{ image.image_tag }}</a></li>
            {% endfor %}

        {% else %}
            <li style="text-align: center;font-size: 50px;">No files yet.</li>
    {% endif %} 
    </ul>




{% endblock %}

share_with_me/drive/templates/images/request_folder.html
{% extends "images/base.html" %} {% block content %}
<div class="center">
    <div class="courses">
        {% if error %}
            <h1 style="font-size:25px;">{{error}}</h1>
        {% else %}    
        <h1>Request</h1>
        <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Request!</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

share_with_me/drive/templates/images/search.html
{% extends "images/base.html" %} {% block content %}

<div class="courses">
  {% if something_found %}
    {% if found_subjects %}
      <h1>Found subjects:</h1>
      <ul class="center_text">
        {% for course in found_subjects %}
          <li style="position:static;display:block;"><a href="{% url 'drive:images:detail_subject' course.course course.specialty course.subject%}">{{ course.course }} | {{ course.specialty }} - {{ course.subject }}</a></li>
        {% endfor %}
      </ul>
    {% endif %} 

    {% if found_specialties %}
      <h1>Found specialties:</h1>
      <ul class="center_text">
        {% for course, specialty in found_specialties %}
        <li style="position:static;display:inline-table;"><a href="{% url 'drive:images:subject' course specialty%}">
              {{course}} - {{ specialty }}</a></li>
        {% endfor %}
      </ul>
    {% endif %} 

    {% if found_files %}
      <h1>Found files:</h1>
      <ul class="center_text">
        {% for file in found_files %}
          <li style="position:static;display:inline-table;"><a href="{% url 'drive:images:detail' file.course_path.path file.id %}">
          {{ file.image_tag }}</a></li>
        {% endfor %}
      </ul>
    {% endif %} 

  {% else %}
      <h1><strong>{{error}}</strong></h1>
  {% endif %} 
</div>
{% endblock %}

share_with_me/drive/templates/images/spec_subject.html
{% extends "images/base.html" %} {% block content %}
<p><a href="{% url 'drive:images:subject' course_id spec %}">Back</a></p>
<h1>Uploading files for: <strong>{{ subj }} </h1>
<h2>Add new image</h2>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Upload image</button>
</form>
{% endblock %}

share_with_me/drive/templates/images/speciality.html
{% extends "images/base.html" %} {% block content %}
<div class="courses">
    <h1>Choose Specialty</h1>
    <div style="position: absolute; top:39.5%; right:80%;" class="circle"></div>
    <div style="position: absolute; top:39.5%; right:15%;" class="circle"></div>
    {% if specialties %}
      <ul>
        {% for specialty in specialties %}
        <li><a href="{% url 'drive:images:subject' course specialty %}">{{specialty}}</a></li>
        {% endfor %}
      </ul>
      <div class="center_text">
              <p>Choose the speciality for which<br>you want to<br>lookup / upload</p>
      </div>
    {% else %}
      <div class="center sharewithme">
          <p><strong>No specialties yet.</strong></p>
      </div>
    {% endif %} 
</div>
{% endblock %}

share_with_me/drive/templates/images/specialty.html
{% extends "images/base.html" %} {% block content %}
<div class="courses">
    <h1>Choose Specialty</h1>
    <div style="position: absolute; top:39.5%; right:80%;" class="circle"></div>
    <div style="position: absolute; top:39.5%; right:15%;" class="circle"></div>
    {% if specialties %}
      <ul>
        {% for specialty in specialties %}
        <li><a href="{% url 'drive:images:subject' course specialty %}">{{specialty}}</a></li>
        {% endfor %}
      </ul>
      <div class="center_text">
              <p>Choose the specialty for which<br>you want to<br>lookup / upload</p>
      </div>
    {% else %}
      <div class="center sharewithme">
          <p><strong>No specialties yet.</strong></p>
      </div>
    {% endif %} 
</div>
{% endblock %}

share_with_me/drive/templates/images/subject.html
{% extends "images/base.html" %} {% block content %}

<div class="courses">
    <h1>Subjects</h1>
    <div style="position: absolute; top:39.5%; right:80%;" class="circle"></div>
    <div style="position: absolute; top:39.5%; right:15%;" class="circle"></div>
    {% if subjects %}
      <ul>
        {% for subject in subjects %}
        <li><a href="{% url 'drive:images:detail_subject' course specialty subject %}">{{ subject }}</a></li>
        {% endfor %}
      </ul>
      <div class="center_text">
                <p>Choose the subject for which<br>you want to<br>lookup / upload</p>
      </div>
    {% else %}
      <div class="center sharewithme">
          <p style="font-size: 30px;"><strong>No subjects yet.</strong></p>
      </div>
    {% endif %}
</div>
{% endblock %}

share_with_me/drive/templates/images/upload_file.html
{% extends "images/base.html" %} {% block content %}
<div class="courses">
    <h1>Uploading</h1>
    <form method="POST" enctype="multipart/form-data">
    <div class="center">
        <div class="courses">
            {% csrf_token %}
            <p><label for="id_description">Description:</label></p>
            <textarea name="description" cols="40" rows="5" id="id_description"></textarea>

            <input style="display:none;" type="file" id="id_file" name="file"/>
            <p><label style="color: white;background-color: #ff0040;" for="id_file">Select file</label></p>
        </div>
    </div>
    <div class="center">
        <button type="submit">Upload file</button>
    </div>
    </form>
</div>
{% endblock %}